services:
  dns-server:
    build: ./conf-dns
    container_name: server-dns
    image: dns-server:lab
    ports:
      - "53:53/tcp"
      - "53:53/udp"

  web1:
    build: ./webtp1
    container_name: web1
    image: web-server1:lab
    ports:
      - "8081:80"
  
  web2:
    build: ./webtp2
    container_name: web2
    image: web-server2:lab
    ports:
    - "8082:80"

  web3:
    build: ./webtp3
    container_name: web3
    image: web-server3:lab
    ports:
    - "8083:80"

  web4:
    build: ./webtp4
    container_name: web4
    image: web-server4:lab
    ports:
    - "8084:80"