version: "3.8"

services:
  dns-server:
    build: ./conf-dns
    container_name: dns-server
    image: dns-server:lab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      labnet:
        ipv4_address: 172.28.0.10

  web1:
    build:
      context: ./webtp1
      dockerfile: Dockerfile
    container_name: web1
    image: web1:lab
    ports:
      - "8081:80"
    depends_on:
      - dns-server
    networks:
      labnet:
        ipv4_address: 172.28.0.11
    dns:
      - 172.28.0.10

  web2:
    build:
      context: ./webtp2
      dockerfile: Dockerfile
    container_name: web2
    image: web2:lab
    ports:
      - "8082:80"
    depends_on:
      - dns-server
    networks:
      labnet:
        ipv4_address: 172.28.0.12
    dns:
      - 172.28.0.10

  web3:
    build:
      context: ./webtp3
      dockerfile: Dockerfile
    container_name: web3
    image: web3:lab
    ports:
      - "8083:80"
    depends_on:
      - dns-server
    networks:
      labnet:
        ipv4_address: 172.28.0.13
    dns:
      - 172.28.0.10

  web4:
    build:
      context: ./webtp4
      dockerfile: Dockerfile
    container_name: web4
    image: web4:lab
    ports:
      - "8084:80"
    depends_on:
      - dns-server
    networks:
      labnet:
        ipv4_address: 172.28.0.14
    dns:
      - 172.28.0.10

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16